In [28]:
import pandas as pd
import numpy as np

In [78]:
df1 = pd.read_csv('circle_chart_data(20240926).csv')
df2 = pd.read_csv(r'C:\Users\user\Desktop\smg\daegeun\Transformed_Data_with_New_Artist.csv')

In [79]:
df1.head()

,date,Rank,Title,Artist,Production,Weekly Views,Genre,Runtime
0,2023-09-24,1,Love Lee,AKMU (악뮤),YG Entertainment,11929992.0,가요 / 댄스,03:00
1,2023-09-24,2,후라이의 꿈,AKMU (악뮤),YG Entertainment,11929992.0,가요 / 블루스/포크,03:25
2,2023-09-24,3,"Smoke (Prod. Dynamicduo, Padi)","다이나믹 듀오 (Dynamic Duo), 이영지",Stone Music Entertainment,4473459.0,가요 / 랩/힙합,03:30
3,2023-09-24,4,Super Shy,NewJeans,ADOR,11655019.0,가요 / 댄스,02:35
4,2023-09-24,5,Seven (feat. Latto) - Clean Ver.,정국,BIGHIT MUSIC,4173726.0,가요 / 댄스,03:04

In [80]:
df2.head()

         date                      Artist     New_Artist
0  2023-09-24                   AKMU (악뮤)             악뮤
1  2023-09-24  다이나믹 듀오 (Dynamic Duo), 이영지  다이나믹 듀오 , 이영지
2  2023-09-24                    NewJeans            뉴진스
3  2023-09-24                          정국             정국
4  2023-09-24                         전소미            전소미

In [81]:
df1 = df1.merge(df2[['date', 'Artist', 'New_Artist']], on=['date', 'Artist'], how='left')

In [82]:
df1.head()

,date,Rank,Title,Artist,Production,Weekly Views,Genre,Runtime,New_Artist
0,2023-09-24,1,Love Lee,AKMU (악뮤),YG Entertainment,11929992.0,가요 / 댄스,03:00,악뮤
1,2023-09-24,2,후라이의 꿈,AKMU (악뮤),YG Entertainment,11929992.0,가요 / 블루스/포크,03:25,악뮤
2,2023-09-24,3,"Smoke (Prod. Dynamicduo, Padi)","다이나믹 듀오 (Dynamic Duo), 이영지",Stone Music Entertainment,4473459.0,가요 / 랩/힙합,03:30,"다이나믹 듀오 , 이영지"
3,2023-09-24,4,Super Shy,NewJeans,ADOR,11655019.0,가요 / 댄스,02:35,뉴진스
4,2023-09-24,5,Seven (feat. Latto) - Clean Ver.,정국,BIGHIT MUSIC,4173726.0,가요 / 댄스,03:04,정국

In [83]:
df1.to_csv('circle_chart_data(20240926)_with_new_artist.csv', index=False)