In [1]:
import pandas as pd

In [4]:
file_path = r'D:\Last_Project\circle_chart_data_with_dates.csv'
df = pd.read_csv(file_path)

In [13]:
# 필요한 컬럼(date, Artist)만 선택
df = df[['date', 'Artist']]

# 데이터의 첫 몇 행을 확인하여 구조를 살펴봅니다
df.head()

         date    Artist
0  2023-01-01  NewJeans
1  2023-01-01        윤하
2  2023-01-01  NewJeans
3  2023-01-01  NewJeans
4  2023-01-01       이영지

In [14]:
# 날짜 데이터를 datetime 형식으로 변환
df['date'] = pd.to_datetime(df['date'])

# 날짜 필터링: 2023-09-24 ~ 2024-09-08
start_date = '2023-09-24'
end_date = '2024-09-08'
df_filtered = df[(df['date'] >= start_date) & (df['date'] <= end_date)]

# 필터링된 데이터 확인
df_filtered.head()

           date                      Artist
7600 2023-09-24                   AKMU (악뮤)
7601 2023-09-24                   AKMU (악뮤)
7602 2023-09-24  다이나믹 듀오 (Dynamic Duo), 이영지
7603 2023-09-24                    NewJeans
7604 2023-09-24                          정국

In [15]:
# 중복된 아티스트 제거: 같은 날짜(date)에서 중복된 아티스트(Artist)를 제거
df_filtered_no_duplicates = df_filtered.drop_duplicates(subset=['date', 'Artist'], keep='first')

# 중복 제거 후 데이터 확인
df_filtered_no_duplicates.head()

           date                      Artist
7600 2023-09-24                   AKMU (악뮤)
7602 2023-09-24  다이나믹 듀오 (Dynamic Duo), 이영지
7603 2023-09-24                    NewJeans
7604 2023-09-24                          정국
7606 2023-09-24                         전소미

In [17]:
# 날짜별로 아티스트가 몇 번씩 나오는지 확인
duplicates_check = df_filtered_no_duplicates.groupby('date')['Artist'].value_counts()

# 중복이 있는 날짜 확인 (카운트가 1보다 큰 경우)
duplicates_check[duplicates_check > 1]

Series([], Name: count, dtype: int64)

In [18]:
# 중복이 없는 데이터 저장
df_filtered_no_duplicates.to_csv('cleaned_circle_chart_data.csv', index=False)